#!/usr/bin/python3
# EASY-INSTALL-ENTRY-SCRIPT: 'slam-iti','console_scripts','sub_n'
__requires__ = 'slam-iti'
import re
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(
        load_entry_point('slam-iti', 'console_scripts', 'sub_n')()
    )
